// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdamorywselfdtxpoqyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYW1vcnl3c2VsZmR0eHBvcXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDc0MTksImV4cCI6MjA2NTQ4MzQxOX0.bKLDDgbJ4yagq0l-wVQ_cO8Fkm4H5ExjvBP58pMykuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);